### ISSUE TITLE
Automatically change the isLocked status of journalnotes more than one day old in the database #106

### ISSUE THREAD

**Issue by themalum** [DCRGraphsNet/DCROpenCaseManager#199]
We should probably make a scheduled task in the database or something similar

**Comment by ThaisCorneliussen** [comment]
Because our database runs on Azure student account, we are not allowed to create jobs that are run automatically at specified times, eg. daily. We have however created the Stored Procedure called LockDocuments which is the stored procedure that needs to be called hourly when the database runs on a real (not student) azure account.
